const {test,expect}=require('@playwright/test');const {execFileSync}=require('node:child_process');
test('objectif personnel : sélection, planning, sauvegarde, progression et contexte IA',async({page,browser})=>{
 test.setTimeout(180000);const c=JSON.parse(execFileSync('scripts/dc.sh',['wp','eval-file','/tests/browser-qcm.php','setup'],{encoding:'utf8'}));let other;
 const login=async(p,user)=>{await p.goto('/connexion/');await p.locator('#user_login').fill(user.login);await p.locator('#user_pass').fill(user.password);await p.locator('#wp-submit').click();await expect(p.locator('#oi-library-title')).toBeVisible();};
 try{
  await login(page,c.student);await page.locator('[data-tab=progress]').click();await expect(page.getByRole('heading',{name:'Ma progression.'})).toBeVisible();await expect(page.getByText('Retrouve les fiches consultées, tes révisions et les séries travaillées.')).toHaveCount(0);await expect(page.locator('.oi-goals-page [data-tab=premium]')).toHaveCount(0);await expect(page.locator('.oi-goals-page').getByText('Retrouver mes favoris')).toHaveCount(0);
  await page.locator('[data-goal-form] [name=title]').fill('Mon partiel personnalisé');await page.locator('[data-goal-form] [name=exam]').selectOption('cas');
  await page.locator('[data-goal-search]').fill('Atelier QCM');for(const id of c.fiches)await page.locator(`[data-goal-select="${id}"]`).check();await expect(page.locator('[data-selection-count]')).toHaveText('2 fiche(s) sélectionnée(s)');
  await page.locator('[name=mode]').selectOption('duration');await page.locator('[name=duration]').fill('2');await page.locator('[name=duration_unit]').selectOption('weeks');await page.locator('[data-goal-form] button[type=submit]').click();await expect(page.locator('.oi-goal-name')).toHaveText('Mon partiel personnalisé');await expect(page.locator('.oi-goal-percent strong')).toHaveText('0%');await expect(page.locator('.oi-goal-calendar article')).not.toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
  await page.reload();await page.locator('[data-tab=progress]').click();await expect(page.locator('.oi-goal-name')).toHaveText('Mon partiel personnalisé');await page.locator(`[data-goal-complete="${c.fiches[0]}"]`).check();await expect(page.locator('.oi-goal-percent strong')).toHaveText('50%');
  await page.locator(`[data-goal-open="${c.fiches[1]}"]`).click();await expect(page.locator('[data-reader-goal]')).toHaveAttribute('aria-pressed','false');await page.locator('[data-reader-goal]').click();await expect(page.locator('[data-reader-goal]')).toHaveAttribute('aria-pressed','true');await page.locator('.oi-main-nav [data-tab=progress]').click();await expect(page.locator('.oi-goal-percent strong')).toHaveText('100%');
  await page.locator('[data-new-goal]').click();await page.locator('[name=title]').fill('Un nouveau cycle');await page.locator('[data-goal-search]').fill('Atelier QCM');await page.locator(`[data-goal-select="${c.fiches[0]}"]`).check();await page.locator('[data-goal-form] button[type=submit]').click();await expect(page.locator('.oi-goal-percent strong')).toHaveText('0%');await expect(page.locator('[data-goal-switch] option')).toHaveCount(2);
  const previous=await page.locator('[data-goal-switch] option').filter({hasText:'Mon partiel personnalisé'}).getAttribute('value');await page.locator('[data-goal-switch]').selectOption(previous);await expect(page.locator('.oi-goal-percent strong')).toHaveText('100%');
  await page.locator('[data-edit-goal]').first().click();await page.locator('[name=title]').fill('Partiel ajusté');await page.locator('[data-goal-form] button[type=submit]').click();await expect(page.locator('.oi-goal-name')).toHaveText('Partiel ajusté');await expect(page.locator('.oi-goal-percent strong')).toHaveText('100%');
  await page.screenshot({path:`.runtime/goals-${test.info().project.name}.png`,fullPage:true});
  let aiRequests=0;page.on('request',r=>{if(r.method()==='POST'&&(r.url().includes('rest_route=%2Foi%2Fv1%2Fai')||r.url().endsWith('/oi/v1/ai')))aiRequests++;});await page.locator('[data-goal-assistant]').click();await expect(page.locator('.oi-chat-context')).toContainText('Partiel ajusté');await expect(page.locator('#oi-question')).toHaveValue(/Partiel ajusté/);expect(aiRequests).toBe(0);
  other=await browser.newContext();const p=await other.newPage();await login(p,c);await p.locator('[data-tab=progress]').click();await expect(p.locator('[data-goal-form]')).toBeVisible();await expect(p.locator('[data-goal-switch]')).toHaveCount(0);
 }finally{if(other)await other.close();execFileSync('scripts/dc.sh',['wp','eval-file','/tests/browser-qcm.php','cleanup',String(c.id),String(c.student.id)],{encoding:'utf8'});}
});
