const {test,expect}=require('@playwright/test');const fs=require('node:fs');const{execFile}=require('node:child_process');const{promisify}=require('node:util');const run=promisify(execFile);const creds=JSON.parse(fs.readFileSync('.runtime/browser-import-user.json','utf8'));
test('atelier Word : aperçu, publication, mise à jour, restauration et protections',async({page,browser})=>{
 test.setTimeout(150000);test.skip(!['desktop','iPhone'].includes(test.info().project.name),'Atelier ordinateur et mobile');
 const cleanup=()=>run('scripts/dc.sh',['wp','eval-file','/tests/browser-imports.php','cleanup',String(creds.id)],{timeout:60000});
 const upload=async(kind)=>{await page.locator('#oi-word-upload input[type=file]').setInputFiles({name:'Atelier technique.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:Buffer.from(creds.files[kind],'base64')});await page.locator('#oi-word-upload button').click();await expect(page.locator('[data-stage]')).toHaveCount(1);};
 try{
  await page.goto('/connexion/');await page.locator('#user_login').fill(creds.login);await page.locator('#user_pass').fill(creds.password);await page.locator('#wp-submit').click();await page.locator('.oi-main-nav [data-tab=imports]').click();await expect(page.getByRole('heading',{name:'Mise à jour Fiches',exact:true})).toBeVisible();
  await expect(page.locator('[data-scan]')).toBeDisabled();await upload('initial');const card=page.locator('[data-stage]');
  await card.locator('[data-field=title]').fill('Atelier technique');await card.locator('[data-field=unit]').selectOption({label:'B1 — Sciences biomédicales'});await card.locator('[data-field=theme]').selectOption({label:'B1 - 01 Fondements biologiques et développement humain'});await card.locator('[data-preview]').click();
  await expect(card.frameLocator('iframe[title="Version proposée"]').locator('body')).toContainText('Version initiale');await expect(card.frameLocator('iframe[title="Version proposée"]').locator('table')).toBeVisible();await expect.poll(()=>card.frameLocator('iframe[title="Version proposée"]').locator('img').evaluate(el=>el.naturalWidth)).toBe(1);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await page.screenshot({path:`.runtime/imports-${test.info().project.name}.png`,fullPage:true});
  await card.locator('[data-publish-one]').click();await expect(page.locator('[data-stage]')).toHaveCount(0);await expect(page.locator('#oi-import-status')).toContainText('1 fiche(s) publiée(s)');
  await upload('updated');await expect(card.locator('[data-field=target]')).not.toHaveValue('0');await card.locator('[data-preview]').click();await expect(card.frameLocator('iframe[title="Version actuellement publiée"]').locator('body')).toContainText('Version initiale');await expect(card.frameLocator('iframe[title="Version proposée"]').locator('body')).toContainText('Version révisée');
  await card.locator('[data-select-stage]').check();await page.locator('[data-publish-selected]').click();await expect(page.locator('[data-stage]')).toHaveCount(0);await page.locator('[data-history]').click();await expect(page.locator('[data-restore]').first()).toBeEnabled();page.once('dialog',d=>d.accept());await page.locator('[data-restore]').first().click();await expect(page.locator('#oi-import-status')).toHaveText('Version restaurée.');
  await page.locator('.oi-main-nav [data-tab=fiches]').click();await page.locator('#oi-query').fill('Atelier technique');await page.locator('#oi-search button').click();await expect(page.locator('#oi-results .oi-card')).toHaveCount(1);await page.locator('#oi-results .oi-card').click();await expect(page.locator('.oi-content')).toContainText('Version initiale');const imageUrl=await page.locator('.oi-content img').getAttribute('src');await expect.poll(()=>page.locator('.oi-content img').evaluate(el=>el.naturalWidth)).toBe(1);
  expect(await page.locator('.oi-content').evaluate(el=>getComputedStyle(el).userSelect)).toBe('none');expect(await page.locator('.oi-content').evaluate(el=>{const e=new Event('copy',{bubbles:true,cancelable:true});el.dispatchEvent(e);return e.defaultPrevented;})).toBe(true);
  await page.emulateMedia({media:'print'});await expect(page.locator('.oi-app')).toBeHidden();await page.emulateMedia({media:'screen'});
  const c=await browser.newContext();const student=JSON.parse(fs.readFileSync('.runtime/browser-user.json','utf8')).projects[test.info().project.name];const p=await c.newPage();await p.goto('/connexion/');await p.locator('#user_login').fill(student.login);await p.locator('#user_pass').fill(student.password);await p.locator('#wp-submit').click();await expect(p.locator('#oi-library-title')).toBeVisible();await expect(p.locator('.oi-main-nav [data-tab=imports]')).toHaveCount(0);const nonce=await p.evaluate(()=>OI.nonce);const refused=await p.request.get('/?rest_route=/oi/v1/imports',{headers:{'X-WP-Nonce':nonce}});expect(refused.status()).toBe(403);expect((await p.request.get(imageUrl)).status()).toBe(403);await c.close();const anon=await browser.newContext();expect((await anon.request.get(imageUrl)).status()).toBe(403);await anon.close();
 }finally{await cleanup();}
});
