const {test,expect}=require('@playwright/test');const {execFileSync}=require('node:child_process');
test('publication directe de 100 fiches sans aperçu : 99 publiées, une erreur isolée puis corrigée',async({page})=>{
 test.setTimeout(180000);const wp=(...args)=>execFileSync('scripts/dc.sh',['wp','eval-file','/tests/browser-imports.php',...args],{encoding:'utf8'});const c=JSON.parse(wp('setup'));
 try{
 const f=JSON.parse(wp('bulk',String(c.id)));let previews=0;const batches=[];page.on('request',r=>{if(r.method()!=='POST')return;const u=decodeURIComponent(r.url());if(u.includes('/preview'))previews++;if(u.includes('/imports/publish'))batches.push(r.postDataJSON().items.length);});
 await page.goto('/connexion/');await page.locator('#user_login').fill(c.login);await page.locator('#user_pass').fill(c.password);await page.locator('#wp-submit').click();await expect(page.locator('#oi-library-title')).toBeVisible({timeout:30000});await page.locator('[data-tab=imports]').click();await expect(page.locator('[data-stage]')).toHaveCount(100,{timeout:30000});await page.locator('[data-select-all]').click();await expect(page.locator('[data-publish-selected]')).toBeEnabled();await page.locator('[data-publish-selected]').click();await expect(page.locator('#oi-import-status')).toContainText('99 fiche(s) publiée(s).',{timeout:120000});await expect(page.locator('[data-stage]')).toHaveCount(1);expect(previews).toBe(0);expect(batches).toEqual([20,20,20,20,20]);await expect(page.locator('#oi-import-status')).toContainText('UE');
 const card=page.locator('[data-stage]');await card.locator('[data-field=unit]').selectOption(String(f.unit));await card.locator('[data-field=theme]').selectOption(String(f.theme));await card.locator('[data-publish-one]').click();await expect(page.locator('#oi-import-status')).toContainText('1 fiche(s) publiée(s).');await expect(page.locator('[data-stage]')).toHaveCount(0);expect(previews).toBe(0);
 }finally{wp('delete',String(c.id));}
});
