const {test,expect}=require('@playwright/test');const fs=require('node:fs');const {execFileSync}=require('node:child_process');
test('Excel QCM : revue admin puis entraînement fiche, thème et UE',async({page,browser})=>{
 test.setTimeout(150000);const c=JSON.parse(execFileSync('scripts/dc.sh',['wp','eval-file','/tests/browser-qcm.php','setup'],{encoding:'utf8'}));let context;
 const login=async(p,user)=>{await p.goto('/connexion/');await p.locator('#user_login').fill(user.login);await p.locator('#user_pass').fill(user.password);await p.locator('#wp-submit').click();await expect(p.locator('#oi-library-title')).toBeVisible();};
 try{
  await login(page,c);await page.locator('[data-tab="qcm-imports"]').click();await expect(page.getByRole('heading',{name:'Gérer les QCM',exact:true})).toBeVisible();
  await page.locator('[data-upload-qcm] input').setInputFiles({name:'B1-TST-981_Atelier_qcm.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(c.file,'base64')});await page.locator('[data-upload-qcm] button').click();const card=page.locator('[data-qcm-stage]').filter({hasText:'Atelier QCM B1-TST-981'});await expect(card).toHaveCount(1);await expect(card.locator('[data-publish-qcm]')).toBeDisabled();await card.locator('[data-preview-qcm]').click();await expect(card.locator('[data-qcm-preview]')).toContainText('1 active(s)');await card.locator('[data-publish-qcm]').click();await expect(card).toHaveCount(0);await expect(page.locator('[data-qcm-status]')).toContainText('1 série(s) publiée(s)');
  context=await browser.newContext({viewport:test.info().project.use.viewport});const student=await context.newPage();await login(student,c.student);await expect(student.locator('[data-tab="qcm-imports"]')).toHaveCount(0);await student.locator('[data-tab=qcm]').click();const launch=student.locator('[data-training-launch]');await expect(launch).toBeVisible();
  for(const [scope,id,total] of [['fiche',c.fiches[0],1],['theme',c.theme,2],['ue',c.unit,2]]){
   await launch.locator('[name=scope]').selectOption(scope);await launch.locator('[name=id]').selectOption(String(id));await launch.locator('[name=count]').selectOption('5');const response=student.waitForResponse(r=>r.url().includes('qcm-sessions')&&r.request().method()==='POST');await launch.locator('button').click();const payload=await(await response).json();expect(JSON.stringify(payload)).not.toContain('"correct"');expect(JSON.stringify(payload)).not.toContain('"explanation"');await expect(student.locator('#oi-quiz-form fieldset')).toHaveCount(total);
  }
  for(const field of await student.locator('#oi-quiz-form fieldset').all()){const checks=field.locator('input[type=checkbox]');if(await checks.count()){await checks.nth(0).check();await checks.nth(2).check();}else await field.locator('input').first().check();}
  await student.locator('#oi-quiz-form button').click();await expect(student.locator('#oi-quiz-result h3')).toHaveText('2 / 2');await expect(student.locator('[data-training-fiche]')).toHaveCount(2);expect(await student.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await student.screenshot({path:`.runtime/qcm-${test.info().project.name}.png`,fullPage:true});
  await student.locator('[data-training-fiche]').first().click();await expect(student.locator('.oi-content')).toContainText('Contenu de test local');
 }finally{if(context)await context.close();execFileSync('scripts/dc.sh',['wp','eval-file','/tests/browser-qcm.php','cleanup',String(c.id),String(c.student.id)],{encoding:'utf8'});}
});
