const {test,expect}=require('@playwright/test');
const {execFileSync}=require('node:child_process');
const login=async(page,c)=>{await page.goto('/connexion/');await page.locator('#user_login').fill(c.login);await page.locator('#user_pass').fill(c.password);await page.locator('#wp-submit').click();await expect(page.locator('#oi-library-title')).toBeVisible();};
test('déblocage : nouvelle page et sélection globale Drive par lots',async({page})=>{
 test.setTimeout(120000);const c=JSON.parse(execFileSync('scripts/dc.sh',['wp','eval-file','/tests/browser-qcm.php','setup'],{encoding:'utf8'}));
 try{
 await login(page,c.student);await expect(page.locator('.oi-main-nav [data-tab=premium]')).toHaveCount(0);await expect(page.getByText('Un peu chaque jour.')).toHaveCount(0);
 if(test.info().project.name==='desktop'){await expect(page.locator('.oi-sidebar-unlock')).toBeVisible();await page.locator('.oi-sidebar-unlock').click();}else await page.goto('/espace-revision/?view=premium');
 await expect(page.locator('.oi-unlock-hero h1')).toHaveText('Accède à tout en illimité pour tes révisions.');await expect(page.locator('.oi-unlock-offer')).toContainText('100 crédits IA supplémentaires');await expect(page.locator('.oi-unlock-price')).toContainText('59');
 expect(await page.locator('.oi-unlock-story img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBeTruthy();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await page.screenshot({path:`.runtime/unlock-${test.info().project.name}.png`,fullPage:true});
 await page.goto('/wp-login.php?action=logout');const confirmation=page.getByRole('link',{name:/déconnecter|log out/i});if(await confirmation.count())await confirmation.first().click();await login(page,c);
 const batches=[];let publishes=0;
 await page.route(/(?:rest_route=.*oi.*v1.*imports|\/wp-json\/oi\/v1\/imports)/,async route=>{const req=route.request();const path=(new URL(req.url()).searchParams.get('rest_route')||new URL(req.url()).pathname.replace('/wp-json',''));if(path==='/oi/v1/imports'){const response=await route.fetch();const data=await response.json();data.drive.connected=true;return route.fulfill({json:data});}if(path.endsWith('/scan'))return route.fulfill({json:{done:true,files:Array.from({length:23},(_,i)=>({id:String(i),name:`Fiche ${i}.docx`,path_label:'B1',version:'0.3',state:i===22?'unchanged':'new',conflict:i===21})),missing:[]}});if(path.endsWith('/prepare')){const ids=req.postDataJSON().ids;batches.push(ids);return route.fulfill({json:ids.map(id=>({id,ok:true,unchanged:false}))});}if(path.endsWith('/publish'))publishes++;return route.continue();});
 await page.goto('/espace-revision/?view=imports');await page.locator('[data-scan]').click();await expect(page.locator('[data-drive-file]')).toHaveCount(23);await page.locator('[data-select-drive]').check();await expect(page.locator('[data-drive-file]:checked')).toHaveCount(21);await page.locator('[data-drive-file="0"]').uncheck();expect(await page.locator('[data-select-drive]').evaluate(e=>e.indeterminate)).toBeTruthy();await page.locator('[data-select-drive]').check();await page.locator('[data-prepare-drive]').click();await expect(page.locator('#oi-import-status')).toContainText('21 préparation(s)');expect(batches.map(x=>x.length)).toEqual([10,10,1]);expect(new Set(batches.flat()).size).toBe(21);expect(publishes).toBe(0);
 }finally{execFileSync('scripts/dc.sh',['wp','eval-file','/tests/browser-qcm.php','cleanup',String(c.id),String(c.student.id)],{encoding:'utf8'});}
});
