<?php
if(!in_array(wp_parse_url(home_url(),PHP_URL_HOST),['localhost','127.0.0.1'],true))throw new RuntimeException('Local only');
$n=0;$check=function($ok,$message)use(&$n){if(!$ok)throw new RuntimeException($message);$n++;};
$catalogue=json_decode(file_get_contents(OI_DIR.'data/programme-2026.json'),true);foreach($catalogue as $unit){$code=$unit['code'];$u=(int)get_term_by('slug','programme-2026-'.strtolower($code),'oi_enseignement')->term_id;foreach($unit['themes'] as $theme){$number=$theme['code'];$check(OI_Drive::classification([$code.' - UE',$number.' - Autre libellé','v0.3 - A RELIRE'])===[$u,0],'Un numéro seul ne définit pas un thème');}}
$rows=json_decode(file_get_contents('/tests/fixtures/drive-classification-2026-10-09.json'),true);foreach($rows as $r)$check(OI_Drive::archived($r['path'])===$r['archived'],'Archive mal reconnue');
$u=(int)get_term_by('slug','programme-2026-b3','oi_enseignement')->term_id;$t=(int)get_term_by('slug','programme-2026-b3-01','oi_theme')->term_id;
$id=wp_insert_post(['post_type'=>'oi_import','post_status'=>'draft','post_title'=>'Fixture classement ancien']);
try{update_post_meta($id,'oi_source',['path'=>'B3 - Medicaments, dispositifs et examens / 01 - Formations et sante mentale initiale / v0.3 - A RELIRE']);$row=array_values(array_filter(OI_Imports::listing()['stages'],fn($r)=>$r['id']===$id))[0];$check($row['unit']===$u&&$row['theme']===0,'Ancien libellé non conforme accepté');$check(!get_post_meta($id,'oi_theme',true),'Lecture ne modifie pas le classement');$manual=(int)get_term_by('slug','programme-2026-b3-02','oi_theme')->term_id;update_post_meta($id,'oi_unit',$u);update_post_meta($id,'oi_theme',$manual);$row=array_values(array_filter(OI_Imports::listing()['stages'],fn($r)=>$r['id']===$id))[0];$check($row['theme']===$manual,'Classement manuel écrasé');}finally{wp_delete_post($id,true);}
$files=[['id'=>'archive','name'=>'B3-TST-001_v0.4.docx','path'=>['B3 - UE','01 - Theme','ARCHIVE - ne pas utiliser']],['id'=>'old','name'=>'B3-TST-001.docx','path'=>['B3 - UE','01 - Theme','v0.2 - VALIDE']],['id'=>'latest','name'=>'B3-TST-001.docx','path'=>['B3 - UE','01 - Theme','v0.3 - A RELIRE']]];
$c=OI_Drive::candidates($files);$check(count($c)===1&&$c[0]['id']==='latest'&&$c[0]['version']==='0.3','Versions annotées/archives mal filtrées');
echo "$n assertions : correspondance prudente, archives et choix manuels.\n";
