<?php
if(!in_array(wp_parse_url(home_url(),PHP_URL_HOST),['localhost','127.0.0.1'],true))throw new RuntimeException('Local only');
$GLOBALS['goal_checks']=0;function goal_check($v,$m){if(!$v)throw new RuntimeException($m);$GLOBALS['goal_checks']++;}
function goal_req($route,$body=null){$r=new WP_REST_Request($body===null?'GET':'POST','/oi/v1/'.$route);if($body!==null)$r->set_body_params($body);return rest_do_request($r);}
$users=[];$posts=[];$pack=OI_Offer::pack();$oldPack=get_post_meta($pack,'oi_fiches',true);
try{
 foreach(['student','other'] as $kind)$users[]=wp_insert_user(['user_login'=>'goals_'.$kind.'_'.wp_generate_password(8,false),'user_pass'=>wp_generate_password(),'role'=>'oi_etudiant']);[$student,$other]=$users;
 $unit=get_term_by('slug','programme-2026-b1','oi_enseignement')->term_id;$theme=get_term_by('slug','programme-2026-b1-01','oi_theme')->term_id;
 foreach(['Premier cours','Deuxième cours','Cours verrouillé'] as $title){$id=wp_insert_post(['post_type'=>'oi_fiche','post_status'=>'publish','post_title'=>$title,'post_content'=>'CONTENU_SECRET_DE_FICHE']);$posts[]=$id;wp_set_object_terms($id,[$unit],'oi_enseignement');wp_set_object_terms($id,[$theme],'oi_theme');}
 update_post_meta($pack,'oi_fiches',array_merge(OI_Model::ids($oldPack),$posts));
 wp_set_current_user(0);goal_check(goal_req('goals')->get_status()===401,'Goals require authentication');goal_check(goal_req('goals/catalogue')->get_status()===401,'Catalogue requires authentication');
 wp_set_current_user($student);$catalogue=goal_req('goals/catalogue')->get_data();$u=array_values(array_filter($catalogue['units'],fn($u)=>$u['id']===$unit))[0];$t=array_values(array_filter($u['themes'],fn($t)=>$t['id']===$theme))[0];goal_check(in_array($posts[0],array_column($t['fiches'],'id'),true),'Programme retains UE/theme/fiche hierarchy');goal_check(!str_contains(wp_json_encode($catalogue),'CONTENU_SECRET'),'Goal metadata does not expose protected content');
 update_user_meta($student,'oi_revision',[$posts[0]=>['revised'=>true]]);
 $body=['title'=>'Mes partiels de novembre','selected'=>[$posts[0],$posts[1]],'exam'=>'cas','schedule'=>['mode'=>'none','timezone'=>'Europe/Paris']];$created=goal_req('goals',$body)->get_data();$g=$created['active'];$id=$g['id'];goal_check($g['percent']===0&&$g['total']===2,'New goal starts at zero independently of old revision state');goal_check(!$g['plan']['enabled'],'Deadline optional');goal_check(!OI_Offer::can_access($student,'FICHE',$posts[0]),'Saving a goal does not unlock content');
 $credits=OI_Credits::balances($student);$r=goal_req("goals/$id/complete",['fiche'=>$posts[0],'done'=>true,'version'=>$g['version']])->get_data();$g=$r['active'];goal_check($g['percent']===50&&$g['completed']===1,'Progress reflects chosen goal only');goal_check(OI_Credits::balances($student)===$credits,'Progress costs no credits');goal_check(OI_Goals::for_fiche($student,$posts[0])['done'],'Reader sees current goal completion');
 goal_check(goal_req("goals/$id/complete",['fiche'=>$posts[1],'done'=>true,'version'=>1])->get_status()===409,'Concurrent stale completion rejected');goal_check(goal_req('goals',$body+['id'=>$id,'version'=>1])->get_status()===409,'Stale edit rejected');
 goal_check(goal_req("goals/$id/complete",['fiche'=>$posts[2],'done'=>true,'version'=>$g['version']])->get_status()===400,'Cannot complete a fiche outside the goal');
 wp_set_current_user($other);goal_check(goal_req('goals')->get_data()['active']===null,'Other account has no access to goal');goal_check(goal_req("goals/$id/activate",[])->get_status()===404,'Other account cannot activate goal');goal_check(goal_req("goals/$id/complete",['fiche'=>$posts[0],'done'=>false,'version'=>$g['version']])->get_status()===404,'Other account cannot update goal');goal_check(goal_req('goals',$body+['id'=>$id,'version'=>$g['version']])->get_status()===404,'Other account cannot edit goal');
 wp_set_current_user($student);$body['selected']=[$posts[0],$posts[2]];$saved=goal_req('goals',$body+['id'=>$id,'version'=>$g['version']])->get_data();$g=$saved['active'];goal_check($g['percent']===50&&$g['selected']===[$posts[0],$posts[2]],'Changing scope preserves only included progress');
 $new=goal_req('goals',['title'=>'Second cycle','selected'=>[$posts[0]],'exam'=>'qcm','schedule'=>['mode'=>'duration','timezone'=>'Europe/Paris','start'=>wp_date('Y-m-d',null,new DateTimeZone('Europe/Paris')),'duration_days'=>14,'weekdays'=>[1,2,3,4,5],'minutes'=>45,'estimate'=>20]])->get_data();goal_check($new['active']['percent']===0&&count($new['goals'])===2,'New cycle leaves old goal intact');goal_check($new['active']['plan']['enabled']&&$new['active']['schedule']['duration_days']===14,'Two-week planning saved');goal_check(str_contains($new['active']['assistant_prompt'],'Second cycle')&&str_contains($new['active']['assistant_prompt'],'qcm'),'Assistant prompt includes objective and exam type');
 $back=goal_req("goals/$id/activate",[])->get_data();goal_check($back['active']['percent']===50&&$back['active']['id']===$id,'Can resume previous goal');
 $invalid=$body;$invalid['selected']=[99999999];goal_check(goal_req('goals',$invalid)->get_status()===400,'Unknown fiche rejected');$invalid=$body;$invalid['selected']=[];goal_check(goal_req('goals',$invalid)->get_status()===400,'Empty objective rejected');
 $invalid=$body;$invalid['schedule']=['mode'=>'deadline','timezone'=>'Europe/Paris','start'=>'2026-02-30','deadline'=>'2026-03-20'];goal_check(goal_req('goals',$invalid)->get_status()===400,'Impossible calendar date rejected');
 $invalid=$body;$invalid['schedule']=['mode'=>'duration','timezone'=>'Europe/Paris','start'=>wp_date('Y-m-d'),'duration_days'=>10,'weekdays'=>[]];goal_check(goal_req('goals',$invalid)->get_status()===400,'Must choose revision days');
 $fake=['selected'=>range(1,7),'done'=>[],'schedule'=>['mode'=>'deadline','timezone'=>'Europe/Paris','start'=>'2026-10-09','deadline'=>'2026-10-15','weekdays'=>[1,3,5],'minutes'=>40,'estimate'=>20]];$plan=OI_Goals::plan($fake,'2026-10-08');goal_check($plan['available_days']===3&&count($plan['unplanned'])===1&&$plan['capacity']===6,'Plan flags insufficient time instead of overbooking');goal_check(array_column($plan['sessions'],'date')===['2026-10-09','2026-10-12','2026-10-14'],'Plan respects selected weekdays');goal_check(max(array_column($plan['sessions'],'minutes'))<=40,'Daily plan fits declared availability');
 $fake['done']=[1=>time(),2=>time()];$plan=OI_Goals::plan($fake,'2026-10-12');goal_check($plan['remaining']===5&&$plan['available_days']===2,'Plan adapts to elapsed time and completion');goal_check(!in_array(1,array_merge(...array_column($plan['sessions'],'fiches')),true),'Completed notions removed from future plan');$plan=OI_Goals::plan($fake,'2026-10-16');goal_check($plan['expired']&&!$plan['sessions']&&count($plan['unplanned'])===5,'Expired deadline reported with remaining work');
 $fake['selected']=[1,2,3];$fake['done']=[];$fake['schedule']=array_merge($fake['schedule'],['start'=>'2026-10-24','deadline'=>'2026-10-26','weekdays'=>[1,6,7],'minutes'=>20]);$plan=OI_Goals::plan($fake,'2026-10-24');goal_check(count($plan['sessions'])===3,'Calendar survives daylight-saving change');
 wp_update_post(['ID'=>$posts[2],'post_status'=>'draft']);$updated=goal_req('goals')->get_data()['active'];goal_check($updated['total']===2&&$updated['percent']===50&&!$updated['fiches'][1]['available'],'Unavailable fiche does not falsely complete objective');
 echo 'Objectifs et planning : '.$GLOBALS['goal_checks']." assertions réussies\n";
}finally{update_post_meta($pack,'oi_fiches',$oldPack);foreach($posts as $id)wp_delete_post($id,true);require_once ABSPATH.'wp-admin/includes/user.php';foreach($users as $user)wp_delete_user($user);}
