<?php
if(!in_array(wp_parse_url(home_url(),PHP_URL_HOST),['localhost','127.0.0.1'],true))throw new RuntimeException('Local only');
$GLOBALS['import_checks']=0;function import_check($ok,$message){if(!$ok)throw new RuntimeException($message);$GLOBALS['import_checks']++;}
function import_req($path,$data=null){$r=new WP_REST_Request($data===null?'GET':'POST','/oi/v1/'.$path);if($data!==null)$r->set_body_params($data);return rest_do_request($r);}
function import_word($path,$text,$hostile=false){$zip=new ZipArchive();$zip->open($path,ZipArchive::CREATE|ZipArchive::OVERWRITE);$xml='<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body><w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>Comprendre</w:t></w:r></w:p><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>'.htmlspecialchars($text).'</w:t></w:r></w:p><w:tbl><w:tr><w:tc><w:p><w:r><w:t>Repère</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Valeur</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p><w:r><w:drawing><a:blip r:embed="rId1"/></w:drawing></w:r></w:p></w:body></w:document>';
 if($hostile)$xml='<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>'.$xml;
 $zip->addFromString('word/document.xml',$xml);$zip->addFromString('word/_rels/document.xml.rels','<Relationships><Relationship Id="rId1" Target="media/example.png"/></Relationships>');$zip->addFromString('word/media/example.png',base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jY1sAAAAASUVORK5CYII='));$zip->close();}
$admin=wp_insert_user(['user_login'=>'import_admin_'.wp_generate_password(8,false),'user_pass'=>wp_generate_password(),'role'=>'administrator']);$student=wp_insert_user(['user_login'=>'import_student_'.wp_generate_password(8,false),'user_pass'=>wp_generate_password(),'role'=>'oi_etudiant']);
$pack=OI_Offer::pack();$oldPack=get_post_meta($pack,'oi_fiches',true);$oldDrive=get_option('oi_drive_credentials',null);$oldToken=get_transient('oi_drive_access');$files=[];$stages=[];$target=0;$history=[];$transport=null;
try{
 wp_set_current_user(0);import_check(import_req('imports')->get_status()===401,'Anonyme refusé');wp_set_current_user($student);import_check(import_req('imports')->get_status()===403,'Étudiant refusé');import_check(import_req('imports/publish',['items'=>[['id'=>1,'token'=>'fake']]])->get_status()===403,'Publication étudiant refusée');
 wp_set_current_user($admin);$tmp=tempnam(sys_get_temp_dir(),'oi-word');$files[]=$tmp;import_word($tmp,'Texte <script>alert(1)</script> pédagogique');$converted=OI_Docx::convert($tmp);import_check(str_contains($converted['html'],'<h2>Comprendre</h2>'),'Titres convertis');import_check(str_contains($converted['html'],'<table>')&&str_contains($converted['html'],'<strong>'),'Tableaux et emphase');import_check(!str_contains($converted['html'],'<script>'),'Texte échappé');import_check(count($converted['images'])===1,'Image embarquée importée');
 $bad=tempnam(sys_get_temp_dir(),'oi-bad');$files[]=$bad;import_word($bad,'malveillant',true);$blocked=false;try{OI_Docx::convert($bad);}catch(Throwable $e){$blocked=true;}import_check($blocked,'Entités XML externes refusées');
 $unit=get_term_by('slug','programme-2026-b1','oi_enseignement')->term_id;$theme=get_term_by('slug','programme-2026-b1-01','oi_theme')->term_id;
 $id=OI_Imports::stage($tmp,'Import technique.docx',['key'=>'test-import-'.wp_generate_password(8,false)]);$stages[]=$id;
 import_check(import_req('imports/publish',['items'=>[['id'=>$id,'token'=>'wrong']]])->get_data()[0]['ok']===false,'Aucune publication sans aperçu');
 $preview=import_req("imports/$id/preview",['title'=>'Import technique','target'=>0,'unit'=>$unit,'theme'=>$theme])->get_data();import_check(str_contains($preview['after'],'admin-post.php?action=oi_fiche_image'),'Images via route protégée');
 $published=import_req('imports/publish',['items'=>[['id'=>$id,'token'=>$preview['token']]]])->get_data()[0];import_check($published['ok'],'Publication Word');$target=$published['target'];import_check(get_post_type($target)==='oi_fiche'&&get_post_status($target)==='publish','Fiche publiée');import_check(in_array($target,OI_Offer::catalogue(),true),'Ajout au catalogue');
 $repeat=import_req('imports/publish',['items'=>[['id'=>$id,'token'=>$preview['token']]]])->get_data()[0];import_check(!$repeat['ok'],'Double publication refusée');
 update_user_meta($student,'oi_packs',[$pack]);update_user_meta($student,'oi_revision',[$target=>['favorite'=>true,'revised'=>true]]);update_post_meta($target,'oi_quiz',[['question'=>'Q','options'=>['A','B'],'correct'=>[0],'explanation'=>'Repère']]);$state=OI_Revision::state($student,$target);$quiz=get_post_meta($target,'oi_quiz',true);
 $file2=tempnam(sys_get_temp_dir(),'oi-word');$files[]=$file2;import_word($file2,'Version mise à jour');$stage2=OI_Imports::stage($file2,'Import technique.docx');$stages[]=$stage2;
 $p=import_req("imports/$stage2/preview",['title'=>'Import technique','target'=>$target,'unit'=>$unit,'theme'=>$theme])->get_data();wp_update_post(['ID'=>$target,'post_content'=>'Modification concurrente']);import_check(!import_req('imports/publish',['items'=>[['id'=>$stage2,'token'=>$p['token']]]])->get_data()[0]['ok'],'Modification concurrente protégée');
 $p=import_req("imports/$stage2/preview",['title'=>'Import technique','target'=>$target,'unit'=>$unit,'theme'=>$theme])->get_data();$pub=import_req('imports/publish',['items'=>[['id'=>$stage2,'token'=>$p['token']]]])->get_data()[0];import_check($pub['ok']&&$pub['target']===$target,'Mise à jour conserve ID');import_check(OI_Revision::state($student,$target)===$state&&get_post_meta($target,'oi_quiz',true)===$quiz,'Progression, favoris et QCM conservés');
 $history=get_posts(['post_type'=>'oi_import_history','post_status'=>'private','post_parent'=>$target,'fields'=>'ids','numberposts'=>-1]);import_check(count($history)===1,'Version précédente sauvegardée');import_check(import_req('imports/history/'.$history[0].'/restore',[])->get_status()===200,'Retour arrière');import_check(get_post_field('post_content',$target)==='Modification concurrente','Contenu antérieur restauré');
 $candidates=OI_Drive::candidates([['id'=>'a','name'=>'Fiche.docx','path'=>['B1','01','v0.3']],['id'=>'b','name'=>'Fiche.docx','path'=>['B1','01','v0.10']]]);import_check(count($candidates)===1&&$candidates[0]['id']==='b','Versions comparées numériquement');$dupes=OI_Drive::candidates([['id'=>'a','name'=>'Fiche.docx','path'=>['B1','01','v0.3']],['id'=>'b','name'=>'Fiche.docx','path'=>['B1','01','v0.3']]]);import_check($dupes[0]['conflict']&&$dupes[1]['conflict'],'Doublon de version signalé');
 // Stable identity across renamed files, new Drive IDs and personalized display titles.
 import_check($converted['title']==='Comprendre','Titre principal extrait du Word');
 $coded=OI_Drive::candidates([['id'=>'old','name'=>'B1-UGR-002_Ancien_v0.3.docx','path'=>['B1','v0.3']],['id'=>'new','name'=>'B1-UGR-002_Nouveau_v0.10.docx','path'=>['Autre dossier','v0.10']]]);
 import_check(count($coded)===1&&$coded[0]['id']==='new'&&$coded[0]['code']==='B1-UGR-002','Code stable malgré titre, chemin et version différents');
 $coded=OI_Drive::candidates([['id'=>'old','name'=>'B1-UGR-002_Ancien_v0.3.docx','path'=>[]],['id'=>'new','name'=>'B1-UGR-002_Nouveau_v0.10.docx','path'=>[]]]);
 import_check(count($coded)===1&&$coded[0]['id']==='new','Version du nom de fichier reconnue');
 $coded=OI_Drive::candidates([['id'=>'a','name'=>'B1-UGR-002_A.docx','path'=>['v0.3']],['id'=>'b','name'=>'B1-UGR-002_B.docx','path'=>['v0.3']]]);
 import_check(count($coded)===2&&$coded[0]['conflict'],'Même code et version avec noms différents : conflit');
 update_post_meta($target,'oi_source_code','B1-UGR-002');update_post_meta($target,'oi_word_title','Ancien titre Word');update_post_meta($target,'oi_title_custom','0');wp_update_post(['ID'=>$target,'post_title'=>'Ancien titre Word']);
 $third=tempnam(sys_get_temp_dir(),'oi-word');$files[]=$third;import_word($third,'Nouveau contenu du Word');
 $auto=OI_Imports::stage($third,'B1-UGR-002_Nom-completement-different_v0.4.docx',['file_id'=>'new-drive-id']);$stages[]=$auto;
 import_check((int)get_post_meta($auto,'oi_target',true)===$target&&get_post_field('post_title',$auto)==='Comprendre','Même fiche et nouveau titre Word proposés automatiquement');
 wp_update_post(['ID'=>$target,'post_title'=>'Titre personnalisé pour les étudiants']);
 $custom=OI_Imports::stage($third,'B1-UGR-002_Encore-renomme_v0.4.docx',['file_id'=>'new-drive-id','key'=>'test-custom-stage']);$stages[]=$custom;
 import_check(get_post_field('post_title',$custom)==='Titre personnalisé pour les étudiants','Titre WordPress modifié manuellement conservé');
 $p=import_req("imports/$custom/preview",['title'=>'Titre personnalisé pour les étudiants','target'=>$target,'unit'=>$unit,'theme'=>$theme])->get_data();
 $pub=import_req('imports/publish',['items'=>[['id'=>$custom,'token'=>$p['token']]]])->get_data()[0];
 import_check($pub['ok']&&$pub['target']===$target&&get_post_meta($target,'oi_title_custom',true)==='1','Publication conserve identité et mémorise titre personnalisé');
 import_check(OI_Revision::state($student,$target)===$state&&get_post_meta($target,'oi_quiz',true)===$quiz,'État utilisateur conservé après changement de nom');
 $ambiguous=wp_insert_post(['post_type'=>'oi_fiche','post_status'=>'draft','post_title'=>'Doublon de code']);
 try{update_post_meta($ambiguous,'oi_source_code','B1-UGR-002');$blocked=false;try{OI_Imports::stage($third,'B1-UGR-002_A.docx');}catch(Throwable $e){$blocked=true;}import_check($blocked,'Deux cibles avec même code bloquent la préparation');}finally{wp_delete_post($ambiguous,true);}
 $heading=tempnam(sys_get_temp_dir(),'oi-title');$files[]=$heading;$zip=new ZipArchive();$zip->open($heading,ZipArchive::CREATE|ZipArchive::OVERWRITE);$zip->addFromString('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Introduction</w:t></w:r></w:p><w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>Sous-section</w:t></w:r></w:p></w:body></w:document>');$zip->close();
 import_check(OI_Docx::convert($heading)['title']==='','Un sous-titre tardif ne devient pas le titre principal');
 $zip->open($heading);$zip->addFromString('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:pPr><w:pStyle w:val="CustomTitle"/></w:pPr><w:r><w:t>Santé </w:t></w:r><w:r><w:t>sexuelle</w:t></w:r></w:p></w:body></w:document>');$zip->addFromString('word/styles.xml','<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:styleId="CustomTitle"><w:name w:val="Title"/></w:style></w:styles>');$zip->close();
 import_check(OI_Docx::convert($heading)['title']==='Santé sexuelle','Style de titre Word et texte en plusieurs fragments reconnus');
 $zip->open($heading);$zip->addFromString('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p/><w:p><w:r><w:t>Puberté : maturation sexuelle et repères</w:t></w:r></w:p><w:p><w:r><w:t>UE B.1 · Sciences biomédicales</w:t></w:r></w:p></w:body></w:document>');$zip->close();
 import_check(OI_Docx::convert($heading)['title']==='Puberté : maturation sexuelle et repères','Titre non stylé avant la ligne UE reconnu');
 $legacy=OI_Imports::stage($heading,'B1-UGR-099_Ancien.docx',['file_id'=>'legacy-drive','key'=>'old-path-key']);$stages[]=$legacy;
 wp_update_post(['ID'=>$legacy,'post_title'=>'B1-UGR-099_Ancien']);$legacySource=get_post_meta($legacy,'oi_source',true);unset($legacySource['word_title']);update_post_meta($legacy,'oi_source',$legacySource);
 $migrated=OI_Imports::stage($heading,'B1-UGR-099_Ancien.docx',['file_id'=>'legacy-drive','key'=>'code:B1-UGR-099']);
 import_check($migrated===$legacy&&get_post_field('post_title',$legacy)==='Puberté : maturation sexuelle et repères','Ancienne préparation actualisée sans doublon');
 // References remain usable in existing preparations and published content.
 $linked=OI_Docx::content('<p>OMS : https://www.who.int/health-topics/sexual-health</p><p>Source : <a href="https://www.sf2h.net/">SF2H</a></p>',0);
 import_check(substr_count($linked,'<a ')===2,'URL brute rendue cliquable sans doubler les liens Word');
 import_check(substr_count($linked,'target="_blank"')===2&&substr_count($linked,'rel="noopener noreferrer"')===2,'Sources ouvertes dans un nouvel onglet isolé');
 import_check(str_contains($linked,'>SF2H</a>')&&str_contains($linked,'https://www.who.int/health-topics/sexual-health'),'Libellé et URL conservés');
 $safe=OI_Docx::source_links('<p><a href="javascript:alert(1)">ref</a><script>alert(1)</script> https://example.org/source.</p>');
 import_check(!str_contains($safe,'href="javascript:')&&!str_contains($safe,'<script>'),'Liens dangereux et scripts refusés');
 import_check(str_contains($safe,'href="https://example.org/source"'),'Ponctuation finale exclue de l’URL');
 import_check(OI_Docx::source_links($linked)===$linked,'Rendu répété sans liens imbriqués');
 // Google transport fixture: no external OAuth or Drive service is claimed as verified.
 $seal=new ReflectionMethod(OI_Drive::class,'seal');update_option('oi_drive_credentials',$seal->invoke(null,['client_id'=>'fixture.apps.googleusercontent.com','client_secret'=>'fixture-secret','refresh_token'=>'fixture-refresh']));delete_transient('oi_drive_access');
 $transport=function($pre,$args,$url)use($tmp){if(str_starts_with($url,'https://oauth2.googleapis.com/token'))$data=['access_token'=>'fixture-access','expires_in'=>3600];elseif(str_starts_with($url,'https://www.googleapis.com/drive/v3/files?'))$data=['files'=>[['id'=>'word-fixture','name'=>'Drive technique.docx','mimeType'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document','modifiedTime'=>'2026-10-08T10:00:00Z','size'=>filesize($tmp)]]];elseif(str_starts_with($url,'https://www.googleapis.com/drive/v3/files/word-fixture?'))return ['headers'=>[],'body'=>file_get_contents($tmp),'response'=>['code'=>200]];else return $pre;return ['headers'=>[],'body'=>wp_json_encode($data),'response'=>['code'=>200]];};add_filter('pre_http_request',$transport,10,3);
 $scan=import_req('imports/drive/scan',['restart'=>true])->get_data();import_check($scan['done']&&count($scan['files'])===1,'Analyse Drive avec transport simulé');$prepared=import_req('imports/drive/prepare',['ids'=>['word-fixture']])->get_data();import_check($prepared[0]['ok'],'Téléchargement et préparation Drive');$stages[]=$prepared[0]['id'];import_check(!str_contains(wp_json_encode(OI_Drive::status()),'fixture-secret'),'Secret absent de l’API de statut');
 $rsa=openssl_pkey_new(['private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA]);openssl_pkey_export($rsa,$private);$public=openssl_pkey_get_details($rsa)['key'];
 $service=OI_Drive::service_credentials(wp_json_encode(['type'=>'service_account','client_email'=>'test@fixture.iam.gserviceaccount.com','private_key'=>$private,'token_uri'=>'https://untrusted.invalid/token']));import_check(!isset($service['token_uri']),'Destination fournie par la clé ignorée');
 $invalid=false;try{OI_Drive::service_credentials('{"type":"service_account","private_key":"invalid"}');}catch(Throwable $e){$invalid=true;}import_check($invalid,'Clé de compte de service invalide refusée');
 $verifier=function($pre,$args,$url)use($public){if($url==='https://oauth2.googleapis.com/token'&&($args['body']['grant_type']??'')==='urn:ietf:params:oauth:grant-type:jwt-bearer'){[$header,$payload,$signature]=explode('.',$args['body']['assertion']);$decode=fn($s)=>base64_decode(strtr($s,'-_','+/'));$claims=json_decode($decode($payload),true);import_check(openssl_verify($header.'.'.$payload,$decode($signature),$public,OPENSSL_ALGO_SHA256)===1,'Signature RSA du compte de service vérifiée');import_check($claims['scope']==='https://www.googleapis.com/auth/drive.readonly'&&$claims['aud']==='https://oauth2.googleapis.com/token'&&$claims['exp']-$claims['iat']===3600&&!isset($claims['sub']),'Autorisation limitée à la lecture sans délégation');}return $pre;};add_filter('pre_http_request',$verifier,5,3);
 try{update_option('oi_drive_credentials',$seal->invoke(null,$service));delete_transient('oi_drive_access');$scan=import_req('imports/drive/scan',['restart'=>true]);import_check($scan->get_status()===200,'Renouvellement avec compte de service');import_check(OI_Drive::status()['mode']==='service_account'&&!str_contains(wp_json_encode(OI_Drive::status()),'PRIVATE KEY'),'Statut sans clé privée');}finally{remove_filter('pre_http_request',$verifier,5);}
 echo 'Import Word / Drive : '.$GLOBALS['import_checks']." assertions réussies\n";
}finally{
 if($transport)remove_filter('pre_http_request',$transport,10);delete_transient('oi_drive_scan_'.$admin);delete_transient('oi_drive_access');if($oldToken)set_transient('oi_drive_access',$oldToken,60);if($oldDrive===null)delete_option('oi_drive_credentials');else update_option('oi_drive_credentials',$oldDrive);
 update_post_meta($pack,'oi_fiches',$oldPack);if($target){foreach(get_posts(['post_type'=>'oi_import_history','post_status'=>'private','post_parent'=>$target,'fields'=>'ids','numberposts'=>-1]) as $id)wp_delete_post($id,true);wp_delete_post($target,true);}foreach($stages as $id)wp_delete_post($id,true);foreach($files as $f)if(is_file($f))unlink($f);require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($admin);wp_delete_user($student);
}
