<?php
if(!in_array(wp_parse_url(home_url(),PHP_URL_HOST),['localhost','127.0.0.1'],true))throw new RuntimeException('Local only');
$n=0;$check=function($ok,$message)use(&$n){if(!$ok)throw new RuntimeException($message);$n++;};
$data=json_decode(file_get_contents(OI_DIR.'data/programme-2026.json'),true);$listing=OI_Imports::listing();$check(count($data)===15&&count($listing['themes'])===158,'Référentiel incomplet');
$counts=['A1'=>2,'A2'=>3,'B1'=>17,'B2'=>4,'B3'=>12,'B4'=>25,'C1'=>6,'C2'=>29,'D1'=>3,'D2'=>18,'D3'=>3,'D4'=>4,'E1'=>4,'E2'=>25,'E3'=>3];
foreach($data as $u){$unit=(int)get_term_by('slug','programme-2026-'.strtolower($u['code']),'oi_enseignement')->term_id;$check(count($u['themes'])===$counts[$u['code']],'Nombre thèmes incorrect');foreach($u['themes'] as $theme){$term=get_term_by('slug','programme-2026-'.strtolower($u['code']).'-'.$theme['code'],'oi_theme');$check($term&&$term->name===$u['code'].' - '.$theme['code'].' '.$theme['name'],'Thème non conforme au document');$check(!get_term_meta($term->term_id,'oi_programme_legacy',true),'Thème de référence marqué ancien');$check(OI_Drive::classification([$u['code'].' - UE',$theme['code'].' - '.$theme['name']])===[$unit,(int)$term->term_id],'Classement exact incorrect');}}
$c2=(int)get_term_by('slug','programme-2026-c2','oi_enseignement')->term_id;$policy=(int)get_term_by('slug','programme-2026-c2-03','oi_theme')->term_id;
$path=['C2 - Sante environnementale et transition ecologique','01 - Fondements politiques et acteurs','v0.3 - A RELIRE'];
$check(OI_Drive::classification($path)===[$c2,0],'Numéro Drive incorrect réinterprété');$check(OI_Drive::classification($path,'Organisation des politiques de santé environnementale en France et dans le monde')===[$c2,$policy],'Titre Word exact ignoré');
$a1=(int)get_term_by('slug','programme-2026-a1','oi_enseignement')->term_id;$check(OI_Drive::classification(['A1 - UE','02 - Sciences infirmieres epistemologie et theories'])===[$a1,0],'Dossier A1 affecté arbitrairement au raisonnement clinique');
$legacy=get_terms(['taxonomy'=>'oi_theme','hide_empty'=>false,'meta_key'=>'oi_programme_legacy','meta_value'=>1]);
foreach($listing['themes'] as $t)$check($t['unit']>0&&!get_term_meta($t['id'],'oi_programme_legacy',true),'Ancien thème ou catégorie libre dans le sélecteur');
$fixtureLegacy=wp_insert_term('Ancien thème de test C2','oi_theme');$legacyId=(int)$fixtureLegacy['term_id'];update_term_meta($legacyId,'oi_programme_unit',$c2);update_term_meta($legacyId,'oi_programme_legacy',1);$legacyC2=get_term($legacyId,'oi_theme');
$id=wp_insert_post(['post_type'=>'oi_import','post_status'=>'draft','post_title'=>'Organisation des politiques de santé environnementale en France et dans le monde','post_content'=>'Contenu temporaire']);
try{update_post_meta($id,'oi_source',['path'=>implode(' / ',$path)]);update_post_meta($id,'oi_unit',$c2);update_post_meta($id,'oi_theme',$legacyC2->term_id);$row=array_values(array_filter(OI_Imports::listing()['stages'],fn($r)=>$r['id']===$id))[0];$check($row['theme']===$policy,'Ancienne préparation non rapprochée');$check((int)get_post_meta($id,'oi_theme',true)===$legacyC2->term_id,'Lecture a muté la préparation');$r=new WP_REST_Request('POST');$r->set_body_params(['id'=>$id,'title'=>'Test','unit'=>$c2,'theme'=>$legacyC2->term_id,'target'=>0]);$check(is_wp_error(OI_Imports::preview($r)),'Publication ancien thème autorisée');}finally{wp_delete_post($id,true);wp_delete_term($legacyId,'oi_theme');}
$before=array_column(OI_Imports::listing()['themes'],'id');update_option('oi_curriculum_version',2);OI_Curriculum::install();$check(array_column(OI_Imports::listing()['themes'],'id')===$before,'Migration non idempotente');
echo "$n assertions, 15 UE, 158 thèmes conformes au document.\n";
