<?php
if(!in_array(wp_parse_url(home_url(),PHP_URL_HOST),['localhost','127.0.0.1'],true))throw new RuntimeException('Local only');
$GLOBALS['qcm_checks']=0;function qc_check($v,$m){if(!$v)throw new RuntimeException($m);$GLOBALS['qcm_checks']++;}
function qc_req($route,$data=null){$r=new WP_REST_Request($data===null?'GET':'POST','/oi/v1/'.$route);if($data!==null)$r->set_body_params($data);return rest_do_request($r);}
$admin=wp_insert_user(['user_login'=>'qcm_admin_'.wp_generate_password(8,false),'user_pass'=>wp_generate_password(),'role'=>'administrator']);$student=wp_insert_user(['user_login'=>'qcm_student_'.wp_generate_password(8,false),'user_pass'=>wp_generate_password(),'role'=>'oi_etudiant']);$other=wp_insert_user(['user_login'=>'qcm_other_'.wp_generate_password(8,false),'user_pass'=>wp_generate_password(),'role'=>'oi_etudiant']);$files=[];$posts=[];$pack=OI_Offer::pack();$oldPack=get_post_meta($pack,'oi_fiches',true);$transport=null;$oldToken=get_transient('oi_drive_access');
try{
 wp_set_current_user(0);qc_check(qc_req('qcm-imports')->get_status()===401,'Admin import requires auth');qc_check(qc_req('qcm-scopes')->get_status()===401,'Scopes require auth');wp_set_current_user($student);qc_check(qc_req('qcm-imports')->get_status()===403,'Student cannot import');
 wp_set_current_user($admin);$unit=get_term_by('slug','programme-2026-b1','oi_enseignement')->term_id;$theme=get_term_by('slug','programme-2026-b1-01','oi_theme')->term_id;
 foreach(['B1-ZZT-901','B1-ZZT-902'] as $code){$id=wp_insert_post(['post_type'=>'oi_fiche','post_status'=>'publish','post_title'=>'Fixture '.$code,'post_author'=>$admin]);$posts[]=$id;update_post_meta($id,'oi_source_code',$code);wp_set_object_terms($id,[$unit],'oi_enseignement');wp_set_object_terms($id,[$theme],'oi_theme');}$target=$posts[0];$second=$posts[1];
 update_post_meta($pack,'oi_fiches',array_merge(OI_Model::ids($oldPack),[$target,$second]));
 $file=tempnam(sys_get_temp_dir(),'qcm');$files[]=$file;copy(OI_DIR.'assets/modele-qcm.xlsx',$file);$zip=new ZipArchive();$zip->open($file);$xml=str_replace('B1-UGR-002','B1-ZZT-901',$zip->getFromName('xl/worksheets/sheet1.xml'));$zip->addFromString('xl/worksheets/sheet1.xml',$xml);$zip->close();
 $rows=OI_Xlsx::read($file);$qs=OI_Xlsx::questions($rows,'B1-ZZT-901');qc_check(count($qs)===1&&$qs[0]['correct']===[0,2],'XLSX inline strings and multiple answers');
 $bad=$rows;$bad[0]['bonnes_reponses']='Z';$blocked=false;try{OI_Xlsx::questions($bad,'B1-ZZT-901');}catch(Throwable $e){$blocked=str_contains($e->getMessage(),'Ligne 2');}qc_check($blocked,'Invalid answer reports line');$blocked=false;try{OI_Xlsx::questions(array_merge($rows,$rows),'B1-ZZT-901');}catch(Throwable $e){$blocked=true;}qc_check($blocked,'Duplicate question codes blocked');
 $evil=tempnam(sys_get_temp_dir(),'qcm');$files[]=$evil;copy($file,$evil);$zip->open($evil);$zip->addFromString('xl/worksheets/sheet1.xml',str_replace('<is>','<f>HYPERLINK("https://example.org")</f><is>',$xml));$zip->close();$blocked=false;try{OI_Xlsx::read($evil);}catch(Throwable $e){$blocked=true;}qc_check($blocked,'Excel formulas rejected');
 $zip->open($evil);$zip->addFromString('xl/worksheets/sheet1.xml','<!DOCTYPE x [<!ENTITY ext SYSTEM "file:///etc/passwd">]>'.$xml);$zip->close();$blocked=false;try{OI_Xlsx::read($evil);}catch(Throwable $e){$blocked=true;}qc_check($blocked,'XML entities rejected');
 $stage=OI_QCM_Imports::stage($file,'B1-ZZT-901_Test_qcm.xlsx');$posts[]=$stage;qc_check((int)get_post($stage)->post_parent===$target,'Matched fiche by code');qc_check(OI_QCM_Imports::stage($file,'B1-ZZT-901_Nom-renomme_qcm.xlsx')===$stage,'Repeated prepare reuses stage');
 qc_check(!qc_req('qcm-imports/publish',['items'=>[['id'=>$stage,'token'=>'fake']]])->get_data()[0]['ok'],'Publish requires preview');
 $preview=qc_req("qcm-imports/$stage/preview",[])->get_data();qc_check($preview['total']===1&&$preview['incoming']===1,'Preview shows bank size');$pub=qc_req('qcm-imports/publish',['items'=>[['id'=>$stage,'token'=>$preview['token']]]])->get_data()[0];qc_check($pub['ok'],'Publish questions');qc_check(!qc_req('qcm-imports/publish',['items'=>[['id'=>$stage,'token'=>$preview['token']]]])->get_data()[0]['ok'],'Duplicate publication blocked');
 qc_check(OI_QCM_Imports::stage($file,'B1-ZZT-901_Renomme_qcm.xlsx')===0,'Unchanged source skipped');
 $bank=OI_Revision::quiz($target,false,200);$bank[0]['code']='B1-ZZT-902-Q001';update_post_meta($second,'oi_quiz',$bank);
 wp_set_current_user($student);qc_check(qc_req('qcm-sessions',['scope'=>'fiche','id'=>$target,'count'=>5])->get_status()===403,'Locked series cannot start');
 update_user_meta($student,'oi_packs',[$pack]);$creditsBefore=OI_Credits::balances($student);$scopes=qc_req('qcm-scopes')->get_data();qc_check(in_array($target,array_column($scopes['fiche'],'id'),true),'Eligible series listed');
 $start=qc_req('qcm-sessions',['scope'=>'theme','id'=>$theme,'count'=>40])->get_data();qc_check(isset($start['id'])&&count($start['quiz'])>=2,'Theme combines questions');$session=$start['id'];qc_check(!str_contains(wp_json_encode($start),'"correct"')&&!str_contains(wp_json_encode($start),'"explanation"'),'Answer keys absent before submit');qc_check(count(array_unique(array_map(fn($q)=>$q['fiche_id'].':'.$q['code'],$start['quiz'])))===count($start['quiz']),'No duplicate questions');qc_check(OI_Credits::balances($student)===$creditsBefore,'Training does not debit credits');
 $snapshot=get_post_meta($session,'oi_session',true);$answers=array_column($snapshot['questions'],'correct');$total=count($answers);
 wp_set_current_user($other);qc_check(qc_req("qcm-sessions/$session/submit",['answers'=>$answers])->get_status()===404,'Other student cannot submit session');
 wp_set_current_user($student);qc_check(qc_req("qcm-sessions/$session/submit",['answers'=>[]])->get_status()===400,'Missing answers rejected');
 $modified=get_post_meta($target,'oi_quiz',true);$modified[0]['correct']=[1];$modified[0]['explanation']='Changed after session start';update_post_meta($target,'oi_quiz',$modified);
 $result=qc_req("qcm-sessions/$session/submit",['answers'=>$answers])->get_data();qc_check($result['score']===$total,'Session uses original correction after bank update');qc_check(isset($result['corrections'][0]['fiche_id']),'Correction points to source fiche');$repeat=qc_req("qcm-sessions/$session/submit",['answers'=>$answers])->get_data();qc_check($repeat===$result&&(int)get_user_meta($student,'oi_qcm_completed',true)===1,'Resubmit idempotent and progress counted once');
 $ue=qc_req('qcm-sessions',['scope'=>'ue','id'=>$unit,'count'=>1])->get_data();qc_check(count($ue['quiz'])===1,'UE scope supported');$single=qc_req('qcm-sessions',['scope'=>'fiche','id'=>$target,'count'=>20])->get_data();qc_check(count($single['quiz'])===1&&$single['available']===1,'Insufficient bank adapts without repeats');
 wp_set_current_user($admin);$zip->open($file);$zip->addFromString('xl/worksheets/sheet1.xml',str_replace('EXEMPLE DE FORMAT','NOUVEL ENONCE',$xml));$zip->close();$stage2=OI_QCM_Imports::stage($file,'B1-ZZT-901_Test_qcm.xlsx');$posts[]=$stage2;$p=qc_req("qcm-imports/$stage2/preview",[])->get_data();$bank=get_post_meta($target,'oi_quiz',true);$bank[0]['question']='Concurrent edit';update_post_meta($target,'oi_quiz',$bank);qc_check(!qc_req('qcm-imports/publish',['items'=>[['id'=>$stage2,'token'=>$p['token']]]])->get_data()[0]['ok'],'Concurrent bank change blocks stale preview');
 $p=qc_req("qcm-imports/$stage2/preview",[])->get_data();qc_check(qc_req('qcm-imports/publish',['items'=>[['id'=>$stage2,'token'=>$p['token']]]])->get_data()[0]['ok'],'Updated question published');qc_check(count(get_post_meta($target,'oi_quiz',true))===1,'Same code updates without duplicate');
 $history=qc_req('qcm-imports/history')->get_data();$restore=array_values(array_filter($history,fn($h)=>$h['restorable']&&$h['title']===get_the_title($target)))[0];qc_check(qc_req('qcm-imports/history/'.$restore['id'].'/restore',[])->get_status()===200,'Restore previous QCM bank');qc_check(get_post_meta($target,'oi_quiz',true)[0]['question']==='Concurrent edit','Restored exact previous bank');
 $archive=$rows;$archive[0]['statut']='archive';$archive=OI_Xlsx::questions($archive,'B1-ZZT-901');update_post_meta($target,'oi_quiz',$archive);qc_check(OI_Revision::quiz($target)===[],'Archived questions excluded');
 // Missing rows are preserved, and a stale preview cannot restore over a later edit.
 $extra=$qs[0];$extra['code']='B1-ZZT-901-Q099';update_post_meta($target,'oi_quiz',[$extra]);
 $zip->open($file);$zip->addFromString('xl/worksheets/sheet1.xml',str_replace('EXEMPLE DE FORMAT','REVISION FINALE',$xml));$zip->close();
 $more=OI_QCM_Imports::stage($file,'B1-ZZT-901_Test_qcm.xlsx');$posts[]=$more;$p=qc_req("qcm-imports/$more/preview",[])->get_data();qc_check(count($p['after'])===2,'Questions absentes du fichier conservées');
 $versions=OI_Drive::candidates([['id'=>'v3','name'=>'B1-ZZT-901_Test_v0.3_qcm.xlsx','path'=>[]],['id'=>'v10','name'=>'B1-ZZT-901_Renomme_v0.10_qcm.xlsx','path'=>[]]]);qc_check(count($versions)===1&&$versions[0]['id']==='v10','Version avant le suffixe qcm reconnue');
 // Google transport is mocked, including a mixed Word/Excel directory.
 $seal=new ReflectionMethod(OI_Drive::class,'seal');set_transient('oi_drive_access',$seal->invoke(null,['token'=>'qcm-fixture']),120);
 $transport=function($pre,$args,$url)use($file){if(str_starts_with($url,'https://www.googleapis.com/drive/v3/files?'))return ['headers'=>[],'body'=>wp_json_encode(['files'=>[['id'=>'excel-fixture','name'=>'B1-ZZT-901_Excel_qcm.xlsx','mimeType'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','modifiedTime'=>'2026-10-08T16:00:00Z','size'=>filesize($file)],['id'=>'word-fixture','name'=>'B1-ZZT-901_Cours.docx','mimeType'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document','modifiedTime'=>'2026-10-08T16:00:00Z']]]),'response'=>['code'=>200]];if(str_starts_with($url,'https://www.googleapis.com/drive/v3/files/excel-fixture?'))return ['headers'=>[],'body'=>file_get_contents($file),'response'=>['code'=>200]];return $pre;};add_filter('pre_http_request',$transport,10,3);
 $scan=qc_req('imports/drive/scan',['kind'=>'qcm','restart'=>true])->get_data();qc_check($scan['done']&&count($scan['files'])===1&&$scan['files'][0]['id']==='excel-fixture','Drive QCM scan selects Excel only');
 $wordScan=qc_req('imports/drive/scan',['restart'=>true])->get_data();qc_check(count($wordScan['files'])===1&&$wordScan['files'][0]['id']==='word-fixture','Word scan remains independent');
 $prepared=qc_req('imports/drive/prepare-qcm',['ids'=>['excel-fixture']])->get_data();qc_check($prepared[0]['ok']&&$prepared[0]['id']===$more,'Drive Excel download and preparation reuse verified');
 echo 'QCM Excel et entraînements : '.$GLOBALS['qcm_checks']." assertions réussies\n";
}finally{
 if($transport)remove_filter('pre_http_request',$transport,10);delete_transient('oi_drive_access');if($oldToken)set_transient('oi_drive_access',$oldToken,60);delete_transient('oi_drive_scan_'.$admin);delete_transient('oi_drive_scan_'.$admin.'_qcm');
 update_post_meta($pack,'oi_fiches',$oldPack);
 foreach([$admin,$student,$other] as $user){foreach(get_posts(['post_type'=>['oi_quiz_session','oi_qcm_history','oi_qcm_import','oi_fiche'],'post_status'=>['publish','draft','private'],'author'=>$user,'fields'=>'ids','numberposts'=>-1]) as $id)wp_delete_post($id,true);require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user($user);}foreach($files as $file)if(is_file($file))unlink($file);
}
