<?php
defined('ABSPATH') || exit;
$oi_signup = esc_url(OI_App::url('register'));
$oi_offer = OI_Offer::public_offer();
$oi_premium_url = esc_url(is_user_logged_in() ? add_query_arg('view','premium',OI_App::url('member')) : add_query_arg('next','premium',OI_App::url('register')));
$oi_login = esc_url(OI_App::url('login'));
$oi_member = esc_url(OI_App::url('member'));
$oi_brand = esc_url(OI_URL . 'assets/brand/logo.png');
$oi_mascot = esc_url(OI_URL . 'assets/brand/mascot.png');
$oi_monitor = esc_url(OI_URL . 'assets/brand/mascot-monitor.png');
$oi_arrow = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>';
$oi_check = '<svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m5 10 3.5 3.5L15 7" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
$oi_spark = '<svg class="oi-symbol" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 1c1.8 7.1 3.9 9.2 11 11-7.1 1.8-9.2 3.9-11 11C10.2 15.9 8.1 13.8 1 12 8.1 10.2 10.2 8.1 12 1Z" fill="currentColor"/></svg>';
$oi_burst = '<svg class="oi-symbol" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 4v16M4 12h16" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="m6 6 12 12M18 6 6 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>';
$oi_heart = '<svg class="oi-symbol" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M20.8 4.9a5.5 5.5 0 0 0-7.8 0L12 6l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.3a5.5 5.5 0 0 0 0-7.8Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/></svg>';
$oi_diagonal = '<svg class="oi-symbol" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 18 12-12M6 6h12v12" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
?>
<div class="oi-landing">
    <a class="oi-skip" href="#oi-main">Aller au contenu</a>
    <header class="oi-site-header oi-container">
        <a class="oi-site-brand" href="<?php echo esc_url(OI_App::url('home')); ?>" aria-label="Objectif Infirmière, accueil"><img class="oi-brand-image" src="<?php echo $oi_brand; ?>" width="1300" height="436" alt="Objectif Infirmière — La référence de la révision en ligne"></a>
        <nav aria-label="Navigation principale" class="oi-public-nav">
            <a class="oi-nav-courses" href="#reviser">Réviser les cours IFSI</a>
            <?php if (is_user_logged_in()) : ?>
                <a class="oi-btn oi-btn-dark oi-nav-signup" href="<?php echo $oi_member; ?>">Mon espace <?php echo $oi_arrow; ?></a>
            <?php else : ?>
                <a class="oi-nav-login" href="<?php echo $oi_login; ?>">Se connecter</a>
                <a class="oi-btn oi-btn-dark oi-nav-signup" href="<?php echo $oi_signup; ?>">S’inscrire <?php echo $oi_arrow; ?></a>
            <?php endif; ?>
        </nav>
    </header>

    <main id="oi-main">
        <section class="oi-hero oi-container" aria-labelledby="oi-hero-title">
            <div class="oi-hero-copy">
                <span class="oi-kicker"><span class="oi-status-dot"></span> TES RÉVISIONS EN SOINS INFIRMIERS</span>
                <h1 id="oi-hero-title">Tes cours d’IFSI.<br>Enfin plus simples<br>à <span class="oi-hero-highlight">réviser.</span></h1>
                <p class="oi-hero-description">Révise avec des fiches claires, des QCM corrigés et un conseiller IA pensé pour les étudiants infirmiers <small>— en préparation.</small></p>
                <div class="oi-hero-actions"><a class="oi-btn oi-btn-dark" href="<?php echo $oi_signup; ?>">Créer mon compte gratuit <?php echo $oi_arrow; ?></a><a class="oi-link-arrow" href="#premium">Découvrir le Premium <span aria-hidden="true"><?php echo $oi_diagonal; ?></span></a></div>
                <p class="oi-hero-note"><span>5 fiches + 5 séries de QCM + 5 crédits IA offerts après confirmation de ton e-mail.</span></p>
                <div class="oi-hero-bottom"><a class="oi-link-arrow" href="#demo">Tester une révision sans compte <?php echo $oi_arrow; ?></a></div>
            </div>
            <div class="oi-hero-visual" aria-label="Aperçu de l’espace de révision">
                <span class="oi-visual-label"><span></span> Objectif : diplôme d’État infirmier</span><svg class="oi-hero-ecg" viewBox="0 0 540 120" fill="none" aria-hidden="true"><path d="M0 63h100l18-18 20 36 24-69 31 99 26-48h321" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                <div class="oi-preview-window">
                    <div class="oi-preview-top"><span class="oi-preview-logo"><?php echo $oi_heart; ?></span><div><strong>Mon carnet de révision</strong><span>Des notions qui prennent tout leur sens.</span></div><span class="oi-preview-avatar">M</span></div>
                    <div class="oi-preview-tabs"><span class="is-active">Mes fiches</span><span>Mes QCM</span><span>Mon assistant <small><?php echo $oi_spark; ?></small></span></div>
                    <div class="oi-preview-greeting"><span>UE 2.2 · LES GRANDES FONCTIONS</span><h2>Comprendre le cœur.<br>Retenir l’essentiel.</h2><span class="oi-greeting-spark" aria-hidden="true"><?php echo $oi_heart; ?></span></div>
                    <div class="oi-preview-search"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" stroke-width="1.6"/><path d="m16 16 4.5 4.5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg>Une UE, une notion, un déclic…<span aria-hidden="true">/</span></div>
                    <div class="oi-preview-section-title"><strong>Au programme aujourd’hui</strong><span>Voir les fiches <?php echo $oi_diagonal; ?></span></div>
                    <div class="oi-preview-cards"><div class="oi-preview-course"><span class="oi-course-icon" aria-hidden="true"><?php echo $oi_heart; ?></span><small>UE 2.2 · BIOLOGIE</small><h3>Le système<br>cardiovasculaire</h3><div><span>Comprendre l’essentiel</span><b><?php echo $oi_diagonal; ?></b></div></div><div class="oi-preview-course oi-preview-course-purple"><span class="oi-course-icon" aria-hidden="true"><?php echo $oi_burst; ?></span><small>UE 2.10 · HYGIÈNE</small><h3>Les précautions<br>standard</h3><div><span>Les bons réflexes</span><b><?php echo $oi_diagonal; ?></b></div></div></div>
                </div>
                <img class="oi-hero-mascot" src="<?php echo $oi_mascot; ?>" width="500" height="500" alt="La mascotte Objectif Infirmière, en blouse et toque de diplômée" fetchpriority="high"><span class="oi-mascot-badge">Cap sur le diplôme <span aria-hidden="true"><?php echo $oi_diagonal; ?></span></span><div class="oi-floating-quiz"><span class="oi-floating-check"><?php echo $oi_check; ?></span><div><strong>Du cours au déclic.</strong><span>Une fiche. Un QCM. Un repère en plus.</span></div><span class="oi-floating-spark" aria-hidden="true"><?php echo $oi_spark; ?></span></div>
                <span class="oi-visual-caption">Aperçu illustratif de l’espace membre</span>

            </div>
        </section>

        <div class="oi-subject-strip" aria-label="Tes révisions au même endroit"><div class="oi-container"><span>LES NOTIONS QUI COMPTENT</span><p>Anatomie <i><?php echo $oi_heart; ?></i> Pharmacologie <i><?php echo $oi_burst; ?></i> Hygiène <i><?php echo $oi_spark; ?></i> Calculs de doses</p></div></div>

        <section id="reviser" class="oi-offer oi-container" aria-labelledby="oi-offer-title">
            <div class="oi-section-heading"><div><span class="oi-eyebrow-public">PENSÉ POUR TES ÉTUDES. ANCRÉ DANS LE SOIN.</span><h2 id="oi-offer-title">Tes cours IFSI.<br><span>Ils prennent tout leur sens.</span></h2></div><p>Entre une UE à valider et un stage à préparer, fais le lien entre ce que tu apprends et le métier qui t’attend.</p></div>
            <div class="oi-offer-grid">
                <article class="oi-feature oi-feature-fiches"><div class="oi-feature-heading"><span class="oi-feature-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><path d="M5 4h11l3 3v13H5V4Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><path d="M9 10h6m-6 4h6m-6 3h3M15 4v4h4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg></span><span>01 / COMPRENDRE</span></div><h3>Les soins s’apprennent.<br>Les repères restent.</h3><p>Anatomie, hygiène, pharmacologie… Choisis 5 fiches avec tes crédits gratuits. Retrouve ensuite tes notions et tes favoris sans nouveau débit.</p><div class="oi-fiche-illustration" aria-hidden="true"><div class="oi-paper"><span>UE 2.10 · INFECTIOLOGIE & HYGIÈNE</span><strong>Précautions<br>standard.</strong><div class="oi-paper-line oi-line-long"></div><div class="oi-paper-line"></div><div class="oi-paper-highlight">Avant le soin, les bons repères.</div><div class="oi-paper-line oi-line-long"></div></div><span class="oi-paper-bookmark"><?php echo $oi_spark; ?></span><span class="oi-paper-tag"><?php echo $oi_check; ?> Dans mes favoris</span></div></article>
                <article class="oi-feature oi-feature-qcm"><div class="oi-feature-heading"><span class="oi-feature-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><rect x="4" y="4" width="16" height="16" rx="4" stroke="currentColor" stroke-width="1.6"/><path d="m8 12 3 3 5-6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></span><span>02 / S’ENTRAÎNER</span></div><h3>Le vrai déclic ?<br>Te tester.</h3><p>Passe de « je crois savoir » à « j’ai compris » avec des QCM et leurs corrections.</p><div class="oi-mini-question" aria-hidden="true"><span>DU COURS À L’AUTO-ÉVALUATION</span><strong>Une notion de soins, bien comprise ?</strong><div><i></i> Je m’entraîne sur une notion</div><div class="is-selected"><i><?php echo $oi_check; ?></i> Je comprends ma réponse <b><?php echo $oi_check; ?></b></div></div></article>
                <article class="oi-feature oi-feature-ai"><div class="oi-feature-heading"><span class="oi-feature-icon" aria-hidden="true"><?php echo $oi_spark; ?></span><span>03 / COMPRENDRE AVEC LE CONSEILLER</span><small class="oi-coming">En préparation</small></div><h3>Une question ?<br>Garde le fil.</h3><p>Ton futur assistant IA personnel pour reformuler une notion de soins infirmiers et faire le lien entre tes cours.</p><div class="oi-ai-illustration"><div><span aria-hidden="true"><?php echo $oi_spark; ?></span><p>« Explique-moi la différence<br>entre antisepsie et asepsie. »</p></div><span class="oi-ai-caption">Un soutien pédagogique, pensé pour tes études.</span></div></article>
            </div>
        </section>

        <section id="demo" class="oi-demo-section" aria-labelledby="oi-demo-title"><div class="oi-container oi-demo-layout"><div class="oi-demo-copy"><span class="oi-eyebrow-public">LE MIEUX, C’EST D’ESSAYER.</span><h2 id="oi-demo-title">Un sujet.<br>Une minute.<br><span>Ton premier déclic.</span></h2><p>Hygiène, calculs ou cardio : choisis une notion de soins infirmiers et teste ce que tu en as retenu.</p><div class="oi-demo-topics" aria-label="Choisir un sujet de démonstration"><button type="button" class="is-active" data-demo-topic="hygiene" aria-pressed="true"><span aria-hidden="true"><?php echo $oi_burst; ?></span> Hygiène des mains <?php echo $oi_arrow; ?></button><button type="button" data-demo-topic="calculs" aria-pressed="false"><span aria-hidden="true">÷</span> Calculs de doses <?php echo $oi_arrow; ?></button><button type="button" data-demo-topic="cardio" aria-pressed="false"><span aria-hidden="true"><?php echo $oi_heart; ?></span> Système cardiovasculaire <?php echo $oi_arrow; ?></button></div><p class="oi-demo-note">Sans compte. Juste pour le plaisir de comprendre.</p></div><div class="oi-demo-card"><div id="oi-demo-panel" class="oi-demo-panel" aria-live="polite"><div class="oi-demo-live-head"><span>SOINS INFIRMIERS</span><span>EXTRAIT DÉCOUVERTE</span></div><h3>Les bons réflexes commencent par les mains.</h3><p class="oi-demo-concept">L’hygiène des mains participe à la prévention de la transmission des micro-organismes. Un geste essentiel, avant comme après le soin.</p><div class="oi-demo-key"><span aria-hidden="true"><?php echo $oi_spark; ?></span><div><strong>Le repère à retenir</strong><p>Les gants ne remplacent pas l’hygiène des mains.</p></div></div><noscript><p>Active JavaScript pour essayer les trois mini-QCM interactifs.</p></noscript></div><div class="oi-demo-card-bottom"><span>Ce premier déclic te donne envie d’aller plus loin ?</span><a class="oi-btn oi-btn-dark" href="<?php echo $oi_signup; ?>" data-demo-signup>Je crée mon espace gratuit <?php echo $oi_arrow; ?></a><small>Une inscription gratuite. Tes révisions, à ton rythme.</small></div></div></div></section>

        <section class="oi-free-start oi-container" aria-labelledby="oi-free-title"><div><span class="oi-eyebrow-public">UN COMPTE GRATUIT. TON PROPRE PARCOURS.</span><h2 id="oi-free-title">Choisis ce que tu veux réviser.</h2><p>Après confirmation de ton e-mail, utilise tes crédits pour explorer les sujets qui t’intéressent. Aucun semestre obligatoire, aucune carte bancaire.</p></div><div class="oi-free-steps"><article><strong>5</strong><h3>fiches à choisir</h3><p>Un crédit pour débloquer une fiche. Elle reste ensuite accessible sans nouveau débit.</p></article><article><strong>5</strong><h3>séries de QCM</h3><p>Débloque une série complète et recommence-la autant que nécessaire.</p></article><article><strong>5</strong><h3>crédits IA</h3><p>Une question traitée avec succès = un crédit. Le conseiller est en préparation ; tes crédits sont conservés.</p></article></div></section>

        <section id="premium" class="oi-premium-public oi-container" aria-labelledby="oi-premium-title"><div class="oi-section-heading"><div><span class="oi-eyebrow-public">À TOI DE CHOISIR LA SUITE.</span><h2 id="oi-premium-title">Toutes tes révisions.<br><span>Un seul paiement.</span></h2></div><p>Commence gratuitement. Passe au Premium quand tu souhaites ouvrir tout le catalogue couvert par le pack.</p></div><div class="oi-comparison-wrap"><table class="oi-comparison"><caption>Comparer le compte Gratuit et le Pack Premium</caption><thead><tr><th scope="col">Ton accès</th><th scope="col">Gratuit</th><th scope="col">Premium</th></tr></thead><tbody><tr><th scope="row">Fiches</th><td>5 au choix</td><td>Toutes les fiches du pack</td></tr><tr><th scope="row">Séries de QCM</th><td>5 au choix</td><td>Toutes les séries du pack</td></tr><tr><th scope="row">Questions IA</th><td>5 crédits offerts</td><td>100 crédits supplémentaires</td></tr><tr><th scope="row">Favoris et progression</th><td>Sur tes contenus débloqués</td><td>Conservés sur tout le pack</td></tr><tr><th scope="row">Paiement</th><td>0 €</td><td>59 € · une seule fois</td></tr><tr><th scope="row">Abonnement</th><td>Aucun</td><td>Aucun</td></tr></tbody></table></div><div class="oi-premium-offer"><div><span class="oi-eyebrow-public">PACK PREMIUM OBJECTIF INFIRMIÈRE</span><h3>Ton prochain chapitre,<br>sans compter les fiches.</h3><ul><li><?php echo (int)$oi_offer['fiches']; ?> fiches IDE publiées dans le pack</li><li><?php echo (int)$oi_offer['qcm']; ?> séries de QCM correspondantes</li><li>Favoris et progression conservés</li><li>100 crédits IA ajoutés aux crédits gratuits restants</li><li>Pas d’expiration automatique des contenus achetés en V1</li></ul></div><div class="oi-premium-buy"><strong>59 €</strong><span>Paiement unique · Sans abonnement</span><a class="oi-btn oi-btn-dark" href="<?php echo $oi_premium_url; ?>">Débloquer mon accès Premium <?php echo $oi_arrow; ?></a><p>Les 100 crédits IA ne se renouvellent pas automatiquement. Aucun prélèvement récurrent.</p></div><p class="oi-premium-disclosure">Version de démonstration : les contenus sont à valider avant commercialisation. Le conseiller IA est en préparation. Paiement Stripe TEST uniquement ; fiscalité définitive à confirmer avant vente réelle. Les quantités ci-dessus proviennent du catalogue publié, pas des contenus à venir.</p></div></section>

        <section class="oi-trust oi-container" aria-labelledby="oi-trust-title"><div><span class="oi-eyebrow-public">DES REPÈRES CLAIRS, SANS FAUSSE PROMESSE.</span><h2 id="oi-trust-title">Pour apprendre.<br>Pour comprendre les soins.</h2></div><div><p>Une fiche pour structurer une notion, une correction pour comprendre une erreur, une progression pour retrouver ton chemin.</p><p>Les contenus de démonstration complètent tes révisions. Tes enseignements IFSI, les recommandations actualisées et les protocoles de stage restent tes références.</p><p>Le conseiller IA s’appuie sur tes fiches accessibles et cite ses sources. Ne saisis aucune donnée de patient.</p></div></section>


        <section id="faq" class="oi-faq oi-container" aria-labelledby="oi-faq-title"><div><span class="oi-eyebrow-public">ON RÉPOND À TES QUESTIONS.</span><h2 id="oi-faq-title">Avant de<br>te lancer.</h2><p>De quoi commencer<br>l’esprit tranquille.</p></div><div class="oi-faq-items"><details><summary>À qui s’adresse Objectif Infirmière ?<span aria-hidden="true">+</span></summary><p>Aux étudiantes et étudiants en soins infirmiers qui veulent structurer leurs révisions, comprendre les notions de cours et s’entraîner avec des QCM, à leur rythme.</p></details><details><summary>Qu’est-ce que je retrouve dans mon espace ?<span aria-hidden="true">+</span></summary><p>Un catalogue de fiches et de séries de QCM à choisir avec tes crédits. Une fiche ou une série débloquée reste accessible. Tes favoris et ta progression sont conservés. Le conseiller IA est encore en préparation.</p></details><details><summary>Est-ce que l’inscription est gratuite ?<span aria-hidden="true">+</span></summary><p>Oui, la création de ton compte est gratuite. Après confirmation de ton adresse e-mail, tu reçois une seule fois 5 crédits Fiche, 5 crédits QCM et 5 crédits IA. Tu peux ensuite choisir le Premium à 59 €, sans abonnement.</p></details><details><summary>Les crédits se renouvellent-ils chaque mois ?<span aria-hidden="true">+</span></summary><p>Non. Les crédits de bienvenue sont attribués une seule fois. Le Premium ajoute une enveloppe totale de 100 crédits IA, sans renouvellement automatique. Une fiche ou une série de QCM déjà débloquée ne consomme plus de crédit.</p></details><details><summary>Que se passe-t-il si le conseiller IA rencontre une erreur ?<span aria-hidden="true">+</span></summary><p>Une demande qui échoue sans fournir de réponse utilisable ne consomme pas de crédit. Le conseiller reste indiqué en préparation tant que ses réponses sourcées ne sont pas disponibles.</p></details><details><summary>Est-ce adapté au téléphone ?<span aria-hidden="true">+</span></summary><p>Oui. Ton espace est conçu pour fonctionner sur téléphone, tablette et ordinateur, directement dans ton navigateur. Tu peux retrouver tes révisions entre deux cours comme chez toi.</p></details><details><summary>Est-ce que la plateforme remplace mes cours ?<span aria-hidden="true">+</span></summary><p>Elle complète tes enseignements et t’aide à réviser. Tes cours IFSI, les recommandations actualisées et les protocoles de ton terrain de stage restent tes références. Les contenus de démonstration sont identifiés comme tels.</p></details></div></section>
        <section class="oi-join oi-container" aria-labelledby="oi-join-title"><div class="oi-join-inner"><div class="oi-join-copy"><span class="oi-eyebrow-public">TON FUTUR COMMENCE AVEC UN PREMIER PAS.</span><h2 id="oi-join-title">Tes premières révisions<br><span>commencent ici.</span></h2><p>Une blouse, un diplôme, un métier qui a du sens. Commence par les notions qui te feront avancer.</p><a class="oi-btn oi-btn-mint" href="<?php echo $oi_signup; ?>">Créer mon compte gratuit <?php echo $oi_arrow; ?></a><span class="oi-join-note">Sans carte bancaire · Premium facultatif à 59 € · IA en préparation</span></div><div class="oi-join-art" aria-hidden="true"><span class="oi-join-orbit"></span><img class="oi-join-mascot" src="<?php echo $oi_monitor; ?>" width="500" height="500" alt="" loading="lazy"><span class="oi-join-label oi-join-label-a">Objectif : IDE.</span><span class="oi-join-label oi-join-label-b">Un déclic à la fois.</span></div></div></section>

    </main>

    <footer class="oi-footer"><div class="oi-container"><div class="oi-footer-top"><a class="oi-site-brand" href="<?php echo esc_url(OI_App::url('home')); ?>"><img class="oi-brand-image" src="<?php echo $oi_brand; ?>" width="1300" height="436" alt="Objectif Infirmière — La référence de la révision en ligne"></a><p>Apprendre aujourd’hui.<br><strong>Prendre soin demain.</strong></p><nav aria-label="Navigation de pied de page"><a href="#reviser">Les révisions</a><a href="#demo">Essayer une notion</a><a href="#faq">Questions fréquentes</a><a href="<?php echo $oi_login; ?>">Mon espace</a></nav></div><div class="oi-footer-bottom"><span>© <?php echo esc_html(wp_date('Y')); ?> Objectif Infirmière</span><span>Avec toi, du premier cours au prochain déclic. <i aria-hidden="true"><?php echo $oi_spark; ?></i></span></div></div></footer>
</div>
